{% set name = "e340py" %}
{% set version = "1.2.2" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  path: ../

build:
  number: 0
  entry_points:
    - dump_comments = e340py.dump_comments:main
    - find_links = e340py.find_links:main
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - setuptools
    - pip
  run:
    - python
    - numpy
    - pandas

test:
  imports:
    - e340py
  requires:
    - numpy
    - pandas
  commands:
    - dump_comments --help


about:
  home: https://clouds.eos.ubc.ca/~phil/courses
  license: MIT
  summary: 'e340 courseware'

extra:
  recipe-maintainers:
    - phaustin
    
